// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

public final class EmployeeOuterClass {
  private EmployeeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string department = 3;</code>
     * @return The department.
     */
    java.lang.String getDepartment();
    /**
     * <code>string department = 3;</code>
     * @return The bytes for department.
     */
    com.google.protobuf.ByteString
        getDepartmentBytes();

    /**
     * <code>float salary = 4;</code>
     * @return The salary.
     */
    float getSalary();
  }
  /**
   * Protobuf type {@code Employee}
   */
  public static final class Employee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Employee)
      EmployeeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      name_ = "";
      department_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Employee();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              department_ = s;
              break;
            }
            case 37: {

              salary_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EmployeeOuterClass.internal_static_Employee_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EmployeeOuterClass.internal_static_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EmployeeOuterClass.Employee.class, EmployeeOuterClass.Employee.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPARTMENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object department_;
    /**
     * <code>string department = 3;</code>
     * @return The department.
     */
    @java.lang.Override
    public java.lang.String getDepartment() {
      java.lang.Object ref = department_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        department_ = s;
        return s;
      }
    }
    /**
     * <code>string department = 3;</code>
     * @return The bytes for department.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDepartmentBytes() {
      java.lang.Object ref = department_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        department_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SALARY_FIELD_NUMBER = 4;
    private float salary_;
    /**
     * <code>float salary = 4;</code>
     * @return The salary.
     */
    @java.lang.Override
    public float getSalary() {
      return salary_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(department_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, department_);
      }
      if (java.lang.Float.floatToRawIntBits(salary_) != 0) {
        output.writeFloat(4, salary_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(department_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, department_);
      }
      if (java.lang.Float.floatToRawIntBits(salary_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, salary_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EmployeeOuterClass.Employee)) {
        return super.equals(obj);
      }
      EmployeeOuterClass.Employee other = (EmployeeOuterClass.Employee) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDepartment()
          .equals(other.getDepartment())) return false;
      if (java.lang.Float.floatToIntBits(getSalary())
          != java.lang.Float.floatToIntBits(
              other.getSalary())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DEPARTMENT_FIELD_NUMBER;
      hash = (53 * hash) + getDepartment().hashCode();
      hash = (37 * hash) + SALARY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSalary());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EmployeeOuterClass.Employee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeOuterClass.Employee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeOuterClass.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeOuterClass.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeOuterClass.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeOuterClass.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeOuterClass.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EmployeeOuterClass.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmployeeOuterClass.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EmployeeOuterClass.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmployeeOuterClass.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EmployeeOuterClass.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EmployeeOuterClass.Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Employee)
        EmployeeOuterClass.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EmployeeOuterClass.internal_static_Employee_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EmployeeOuterClass.internal_static_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EmployeeOuterClass.Employee.class, EmployeeOuterClass.Employee.Builder.class);
      }

      // Construct using EmployeeOuterClass.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        department_ = "";

        salary_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EmployeeOuterClass.internal_static_Employee_descriptor;
      }

      @java.lang.Override
      public EmployeeOuterClass.Employee getDefaultInstanceForType() {
        return EmployeeOuterClass.Employee.getDefaultInstance();
      }

      @java.lang.Override
      public EmployeeOuterClass.Employee build() {
        EmployeeOuterClass.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public EmployeeOuterClass.Employee buildPartial() {
        EmployeeOuterClass.Employee result = new EmployeeOuterClass.Employee(this);
        result.id_ = id_;
        result.name_ = name_;
        result.department_ = department_;
        result.salary_ = salary_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EmployeeOuterClass.Employee) {
          return mergeFrom((EmployeeOuterClass.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EmployeeOuterClass.Employee other) {
        if (other == EmployeeOuterClass.Employee.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDepartment().isEmpty()) {
          department_ = other.department_;
          onChanged();
        }
        if (other.getSalary() != 0F) {
          setSalary(other.getSalary());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EmployeeOuterClass.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EmployeeOuterClass.Employee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object department_ = "";
      /**
       * <code>string department = 3;</code>
       * @return The department.
       */
      public java.lang.String getDepartment() {
        java.lang.Object ref = department_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          department_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string department = 3;</code>
       * @return The bytes for department.
       */
      public com.google.protobuf.ByteString
          getDepartmentBytes() {
        java.lang.Object ref = department_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          department_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string department = 3;</code>
       * @param value The department to set.
       * @return This builder for chaining.
       */
      public Builder setDepartment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        department_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string department = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDepartment() {
        
        department_ = getDefaultInstance().getDepartment();
        onChanged();
        return this;
      }
      /**
       * <code>string department = 3;</code>
       * @param value The bytes for department to set.
       * @return This builder for chaining.
       */
      public Builder setDepartmentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        department_ = value;
        onChanged();
        return this;
      }

      private float salary_ ;
      /**
       * <code>float salary = 4;</code>
       * @return The salary.
       */
      @java.lang.Override
      public float getSalary() {
        return salary_;
      }
      /**
       * <code>float salary = 4;</code>
       * @param value The salary to set.
       * @return This builder for chaining.
       */
      public Builder setSalary(float value) {
        
        salary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float salary = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSalary() {
        
        salary_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Employee)
    }

    // @@protoc_insertion_point(class_scope:Employee)
    private static final EmployeeOuterClass.Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EmployeeOuterClass.Employee();
    }

    public static EmployeeOuterClass.Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      @java.lang.Override
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public EmployeeOuterClass.Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmployeesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Employees)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    java.util.List<EmployeeOuterClass.Employee> 
        getEmployeesList();
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    EmployeeOuterClass.Employee getEmployees(int index);
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    int getEmployeesCount();
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    java.util.List<? extends EmployeeOuterClass.EmployeeOrBuilder> 
        getEmployeesOrBuilderList();
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    EmployeeOuterClass.EmployeeOrBuilder getEmployeesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Employees}
   */
  public static final class Employees extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Employees)
      EmployeesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Employees.newBuilder() to construct.
    private Employees(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employees() {
      employees_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Employees();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Employees(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                employees_ = new java.util.ArrayList<EmployeeOuterClass.Employee>();
                mutable_bitField0_ |= 0x00000001;
              }
              employees_.add(
                  input.readMessage(EmployeeOuterClass.Employee.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          employees_ = java.util.Collections.unmodifiableList(employees_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EmployeeOuterClass.internal_static_Employees_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EmployeeOuterClass.internal_static_Employees_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EmployeeOuterClass.Employees.class, EmployeeOuterClass.Employees.Builder.class);
    }

    public static final int EMPLOYEES_FIELD_NUMBER = 1;
    private java.util.List<EmployeeOuterClass.Employee> employees_;
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    @java.lang.Override
    public java.util.List<EmployeeOuterClass.Employee> getEmployeesList() {
      return employees_;
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends EmployeeOuterClass.EmployeeOrBuilder> 
        getEmployeesOrBuilderList() {
      return employees_;
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    @java.lang.Override
    public int getEmployeesCount() {
      return employees_.size();
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    @java.lang.Override
    public EmployeeOuterClass.Employee getEmployees(int index) {
      return employees_.get(index);
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    @java.lang.Override
    public EmployeeOuterClass.EmployeeOrBuilder getEmployeesOrBuilder(
        int index) {
      return employees_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < employees_.size(); i++) {
        output.writeMessage(1, employees_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < employees_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, employees_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EmployeeOuterClass.Employees)) {
        return super.equals(obj);
      }
      EmployeeOuterClass.Employees other = (EmployeeOuterClass.Employees) obj;

      if (!getEmployeesList()
          .equals(other.getEmployeesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEmployeesCount() > 0) {
        hash = (37 * hash) + EMPLOYEES_FIELD_NUMBER;
        hash = (53 * hash) + getEmployeesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EmployeeOuterClass.Employees parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeOuterClass.Employees parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeOuterClass.Employees parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeOuterClass.Employees parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeOuterClass.Employees parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeOuterClass.Employees parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeOuterClass.Employees parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EmployeeOuterClass.Employees parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmployeeOuterClass.Employees parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EmployeeOuterClass.Employees parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmployeeOuterClass.Employees parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EmployeeOuterClass.Employees parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EmployeeOuterClass.Employees prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Employees}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Employees)
        EmployeeOuterClass.EmployeesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EmployeeOuterClass.internal_static_Employees_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EmployeeOuterClass.internal_static_Employees_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EmployeeOuterClass.Employees.class, EmployeeOuterClass.Employees.Builder.class);
      }

      // Construct using EmployeeOuterClass.Employees.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEmployeesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (employeesBuilder_ == null) {
          employees_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          employeesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EmployeeOuterClass.internal_static_Employees_descriptor;
      }

      @java.lang.Override
      public EmployeeOuterClass.Employees getDefaultInstanceForType() {
        return EmployeeOuterClass.Employees.getDefaultInstance();
      }

      @java.lang.Override
      public EmployeeOuterClass.Employees build() {
        EmployeeOuterClass.Employees result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public EmployeeOuterClass.Employees buildPartial() {
        EmployeeOuterClass.Employees result = new EmployeeOuterClass.Employees(this);
        int from_bitField0_ = bitField0_;
        if (employeesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            employees_ = java.util.Collections.unmodifiableList(employees_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.employees_ = employees_;
        } else {
          result.employees_ = employeesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EmployeeOuterClass.Employees) {
          return mergeFrom((EmployeeOuterClass.Employees)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EmployeeOuterClass.Employees other) {
        if (other == EmployeeOuterClass.Employees.getDefaultInstance()) return this;
        if (employeesBuilder_ == null) {
          if (!other.employees_.isEmpty()) {
            if (employees_.isEmpty()) {
              employees_ = other.employees_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEmployeesIsMutable();
              employees_.addAll(other.employees_);
            }
            onChanged();
          }
        } else {
          if (!other.employees_.isEmpty()) {
            if (employeesBuilder_.isEmpty()) {
              employeesBuilder_.dispose();
              employeesBuilder_ = null;
              employees_ = other.employees_;
              bitField0_ = (bitField0_ & ~0x00000001);
              employeesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEmployeesFieldBuilder() : null;
            } else {
              employeesBuilder_.addAllMessages(other.employees_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EmployeeOuterClass.Employees parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EmployeeOuterClass.Employees) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<EmployeeOuterClass.Employee> employees_ =
        java.util.Collections.emptyList();
      private void ensureEmployeesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          employees_ = new java.util.ArrayList<EmployeeOuterClass.Employee>(employees_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          EmployeeOuterClass.Employee, EmployeeOuterClass.Employee.Builder, EmployeeOuterClass.EmployeeOrBuilder> employeesBuilder_;

      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public java.util.List<EmployeeOuterClass.Employee> getEmployeesList() {
        if (employeesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(employees_);
        } else {
          return employeesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public int getEmployeesCount() {
        if (employeesBuilder_ == null) {
          return employees_.size();
        } else {
          return employeesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public EmployeeOuterClass.Employee getEmployees(int index) {
        if (employeesBuilder_ == null) {
          return employees_.get(index);
        } else {
          return employeesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder setEmployees(
          int index, EmployeeOuterClass.Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.set(index, value);
          onChanged();
        } else {
          employeesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder setEmployees(
          int index, EmployeeOuterClass.Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.set(index, builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder addEmployees(EmployeeOuterClass.Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.add(value);
          onChanged();
        } else {
          employeesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder addEmployees(
          int index, EmployeeOuterClass.Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.add(index, value);
          onChanged();
        } else {
          employeesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder addEmployees(
          EmployeeOuterClass.Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.add(builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder addEmployees(
          int index, EmployeeOuterClass.Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.add(index, builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder addAllEmployees(
          java.lang.Iterable<? extends EmployeeOuterClass.Employee> values) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, employees_);
          onChanged();
        } else {
          employeesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder clearEmployees() {
        if (employeesBuilder_ == null) {
          employees_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          employeesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder removeEmployees(int index) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.remove(index);
          onChanged();
        } else {
          employeesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public EmployeeOuterClass.Employee.Builder getEmployeesBuilder(
          int index) {
        return getEmployeesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public EmployeeOuterClass.EmployeeOrBuilder getEmployeesOrBuilder(
          int index) {
        if (employeesBuilder_ == null) {
          return employees_.get(index);  } else {
          return employeesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public java.util.List<? extends EmployeeOuterClass.EmployeeOrBuilder> 
           getEmployeesOrBuilderList() {
        if (employeesBuilder_ != null) {
          return employeesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(employees_);
        }
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public EmployeeOuterClass.Employee.Builder addEmployeesBuilder() {
        return getEmployeesFieldBuilder().addBuilder(
            EmployeeOuterClass.Employee.getDefaultInstance());
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public EmployeeOuterClass.Employee.Builder addEmployeesBuilder(
          int index) {
        return getEmployeesFieldBuilder().addBuilder(
            index, EmployeeOuterClass.Employee.getDefaultInstance());
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public java.util.List<EmployeeOuterClass.Employee.Builder> 
           getEmployeesBuilderList() {
        return getEmployeesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          EmployeeOuterClass.Employee, EmployeeOuterClass.Employee.Builder, EmployeeOuterClass.EmployeeOrBuilder> 
          getEmployeesFieldBuilder() {
        if (employeesBuilder_ == null) {
          employeesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              EmployeeOuterClass.Employee, EmployeeOuterClass.Employee.Builder, EmployeeOuterClass.EmployeeOrBuilder>(
                  employees_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          employees_ = null;
        }
        return employeesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Employees)
    }

    // @@protoc_insertion_point(class_scope:Employees)
    private static final EmployeeOuterClass.Employees DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EmployeeOuterClass.Employees();
    }

    public static EmployeeOuterClass.Employees getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Employees>
        PARSER = new com.google.protobuf.AbstractParser<Employees>() {
      @java.lang.Override
      public Employees parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employees(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Employees> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employees> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public EmployeeOuterClass.Employees getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Employee_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employees_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Employees_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016employee.proto\"H\n\010Employee\022\n\n\002id\030\001 \001(\005" +
      "\022\014\n\004name\030\002 \001(\t\022\022\n\ndepartment\030\003 \001(\t\022\016\n\006sa" +
      "lary\030\004 \001(\002\")\n\tEmployees\022\034\n\temployees\030\001 \003" +
      "(\0132\t.Employeeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Employee_descriptor,
        new java.lang.String[] { "Id", "Name", "Department", "Salary", });
    internal_static_Employees_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Employees_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Employees_descriptor,
        new java.lang.String[] { "Employees", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
